"""reports

Revision ID: 85ac64a42408
Revises: 7763afe531f9
Create Date: 2026-07-15 05:09:12.564125
"""
from alembic import op
import sqlalchemy as sa


revision = '85ac64a42408'
down_revision = '7763afe531f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('executive', 'mission_assurance', 'incident', 'threat_intel', 'quantum_readiness', name='reportkind', native_enum=False, length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_kind'), 'reports', ['kind'], unique=False)
    op.create_index(op.f('ix_reports_subject_id'), 'reports', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_subject_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_kind'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
