"""threat indicators and matches

Revision ID: 7763afe531f9
Revises: af1afcb08281
Create Date: 2026-07-15 03:59:42.784892
"""
from alembic import op
import sqlalchemy as sa


revision = '7763afe531f9'
down_revision = 'af1afcb08281'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_indicators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('indicator_type', sa.Enum('ip', 'domain', 'url', 'file_hash', 'email', name='indicatortype', native_enum=False, length=30), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('malware', 'phishing', 'c2', 'scanner', 'apt', 'jamming', 'unknown', name='threatcategory', native_enum=False, length=30), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='alertseverity', native_enum=False, length=30), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_type', 'value', name='uq_indicator_type_value')
    )
    op.create_index(op.f('ix_threat_indicators_active'), 'threat_indicators', ['active'], unique=False)
    op.create_index(op.f('ix_threat_indicators_category'), 'threat_indicators', ['category'], unique=False)
    op.create_index(op.f('ix_threat_indicators_indicator_type'), 'threat_indicators', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_threat_indicators_severity'), 'threat_indicators', ['severity'], unique=False)
    op.create_index(op.f('ix_threat_indicators_source'), 'threat_indicators', ['source'], unique=False)
    op.create_index(op.f('ix_threat_indicators_value'), 'threat_indicators', ['value'], unique=False)
    op.create_table('threat_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('indicator_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('matched_on', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['threat_indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_id', 'asset_id', name='uq_match_indicator_asset')
    )
    op.create_index(op.f('ix_threat_matches_asset_id'), 'threat_matches', ['asset_id'], unique=False)
    op.create_index(op.f('ix_threat_matches_indicator_id'), 'threat_matches', ['indicator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_matches_indicator_id'), table_name='threat_matches')
    op.drop_index(op.f('ix_threat_matches_asset_id'), table_name='threat_matches')
    op.drop_table('threat_matches')
    op.drop_index(op.f('ix_threat_indicators_value'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_source'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_severity'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_indicator_type'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_category'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_active'), table_name='threat_indicators')
    op.drop_table('threat_indicators')
    # ### end Alembic commands ###
